### ISSUE TITLE
Add frugal-uuid to default Quicklisp dist

### ISSUE THREAD

**Issue by kilianmh** [ak-coram/cl-frugal-uuid#6]
- I am myself user of Ultralisp. However, systems which are distributed in the default Quicklisp dist, can only depend on `frugal-uuid`, if it (and dependencies), are in the default dist.
- Do you want to open the [issue in Quicklisp Projects](https://github.com/quicklisp/quicklisp-projects/issues)? Else I can also do it.
- The same has to be done for [trivial-clock](https://github.com/ak-coram/cl-trivial-clock). Alternatively, switching to [local-time](https://github.com/dlowe-net/local-time), or [precise-time](https://github.com/Shinmera/precise-time) might be an option.

**Comment by ak-coram** [comment]
Hi, thank you for your interest in this library. I have no issues with it being included in the default Quicklisp dist, feel free to request its inclusion. The same goes for triviaĺ-clock.

**Comment by ak-coram** [comment]
@kilianmh: we've made it into the latest Quicklisp dist!
